FROM rust:1.81.0-bookworm

RUN rustup component add rustfmt

# For inputting Japanese
RUN apt-get update -y
RUN apt-get install -y locales && \
    locale-gen ja-JP.UTF-8 && \
    localedef -f UTF-8 -i ja_JP ja_JP && \
    echo "export LANG=ja_JP.UTF-8" >> /root/.bashrc
